server:
  session-timeout: 1800
  tomcat:
        max-threads: 1000
        min-spare-threads: 30
  port: 8080
  uri-encoding: utf-8
  context-path: /admin

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: true
  resources: # 指定静态资源的路径
          static-locations: classpath:/static/,classpath:/views/
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  #指定bean所在包
  typeAliasesPackage: com.dm.zos.**.entity
  #指定映射文件
  mapper-locations: classpath:mapper/**/*.xml
mapper:
  #mapper
  #mappers 多个接口时逗号隔开
  mappers: BaseMapper

#pagehelper分页插件
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: countSql



